baseURL: "https://mzoengc.github.io/"
title: Mary Cheung
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    # profile-mode
    profileMode:
      enabled: true # needs to be explicitly set
      title: Mary Cheung
      subtitle: "Software Engineer | Full Stack Developer"
      imageUrl: "https://github.com/mzoengc.png"
      imageWidth: 120
      imageHeight: 120
      imageTitle: Mary Cheung
  #   menu:
  #     main:
  #       - name: Posts
  #         url: /posts/
  #         weight: 5
  #       - name: Tags
  #         url: /tags/
  #         weight: 10
  # zh-tw:
  #   languageName: "中文"
  #   weight: 2
  #   # profile-mode
  #   profileMode:
  #     enabled: true # needs to be explicitly set
  #     title: Mary Cheung
  #     subtitle: "軟件工程師 | 全端工程师"
  #     imageUrl: "https://github.com/mzoengc.png"
  #     imageWidth: 120
  #     imageHeight: 120
  #     imageTitle: Mary Cheung
  #   menu:
  #     main:
  #       - name: 文章
  #         url: /posts/
  #         weight: 5
  #       - name: 標籤
  #         url: /tags/
  #         weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Mary Cheung
  description: "A website to introduce myself"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  displayFullLangName: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 20

  # profile-mode
  # profileMode:
  #   enabled: true # needs to be explicitly set
  #   title: Mary Cheung
  #   subtitle: "Software Engineer | Full Stack Developer"
  #   imageUrl: "https://github.com/mzoengc.png"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: Mary Cheung

  # home-info mode
  # homeInfoParams:
  #   Title: "Hi there \U0001F44B"
  #   Content: Welcome to my blog

  socialIcons:
    - name: github
      url: "https://github.com/mzoengc"
    - name: linkedin
      url: "https://ca.linkedin.com/in/marymwc"
    - name: twitter
      url: "https://twitter.com/mzhkca"
    - name: instagram
      url: "https://instagram.com/mzhkca"
    - name: facebook
      url: "https://facebook.com/mzhkca"
    - name: email
      url: "mailto:mingwai.cheung@pm.me"

  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/mzoengc/mzoengc.github.io/tree/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai